python -u run.py \
  --train \
  --use_gpu \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model Transformer \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862